### ISSUE TITLE
Can't generate excel output

### ISSUE THREAD

**Issue by alpaykocak** [jdemetra/jdemetra-app#359]
Dear All,

I hope you are fine since we met. I have problem with generating excel output after multi processing done.
Actually, I had not this type of problem before I clean my computer. I deleted some files those I thought they were not necessary. In summary, I previously can generate excel output but now I can not with Jdemetra 2.1.0. Now, I explain my problem. 
First exception:
java.lang.NullPointerException
	at ec.tss.sa.output.DefaultSummary.<init>(DefaultSummary.java:40)
	at ec.tss.sa.output.SpreadsheetOutput.process(SpreadsheetOutput.java:57)
	at ec.tss.sa.output.SpreadsheetOutput.process(SpreadsheetOutput.java:42)
	at ec.nbdemetra.sa.actions.Output$1.doInBackground(Output.java:104)
	at ec.nbdemetra.sa.actions.Output$1.doInBackground(Output.java:91)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at ec.nbdemetra.sa.actions.Output$1.done(Output.java:115)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
[catch] at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Second: I do not know it is related but also I have problem with Nowcasting module. I also used it succesfully but now, I can not. 

I uninstalled/re-installed JDemetra+ for several times. I also have JDK8. So I do not think this problem about Java version. I feel I have to ste up something but what? 

Please help me.
Best regards,
Alpay

**Comment by pinkfairystardust** [comment]
Hello! You can try uninstall and reinstall Java then reinstall also Jdemetra

**Comment by charphi** [comment]
Hi,
We are about to release a new version of JD+ (v2.2.0).
So, this bug might already been solved.
Could you try the latest release candidate of v2.2.0 instead of v2.1.0 ?

**Comment by alpaykocak** [comment]
Thank you, I will wait.


Outlook<http://aka.ms/weboutlook>'tan gönderildi


________________________________
Gönderen: Philippe Charles <notifications@github.com>
Gönderildi: 12 Haziran 2017 Pazartesi 10:51
Kime: jdemetra/jdemetra-app
Bilgi: alpaykocak; Author
Konu: Re: [jdemetra/jdemetra-app] Can't generate excel output (#359)


Hi,
We are about to release a new version of JD+ (v2.2.0).
So, this bug might already been solved.
Could you try the latest release candidate of v2.2.0 instead of v2.1.0 ?

**Comment by charphi** [comment]
The purpose of a release candidate is to detect and correct bugs before a final release.
I would be better if you could try the latest release candidate with your problem and tell us if it solves it.
(download the RC3 at https://github.com/jdemetra/jdemetra-app/releases/download/v2.2.0-rc3/jdemetra-2.2.0-rc3.zip, uncompress it somewhere and run `bin/nbdemetra64.exe`)
Thanks in advance.

**Comment by sungreen** [comment]
Ok! in version 2.2.0-RC3 already works

**Comment by charphi** [comment]
Ok; Thanks.

**Comment by sungreen** [comment]
the file is generated, but saved not in that folder (~/nbdimetra/bin/Demetra+/)
for example, I am selected folder ~/myfolder,  but output generated in folder ~/nbdemetra/bin/Demetra+/myworksheet/SAProcessing-1/demetra.xlsx

**Comment by charphi** [comment]
I've just tested and it works fine on Linux.
