### ISSUE TITLE
Application does not start in linux mint

### ISSUE THREAD

**Issue by sungreen** [jdemetra/jdemetra-app#552]
Hi! Application does not start in linux mint
-------------------------------------------------------------------------------
>Log Session: Sunday, November 22, 2020 at 8:27:36 AM Moscow Standard Time
>System Info: 
  Product Version         = JDemetra+ 201609300101
  Operating System        = Linux version 5.4.0-54-generic running on amd64
  Java; VM; Vendor        = 15.0.1; Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 15.0.1+9-18
  Java Home               = /usr/lib/jvm/java-15-oracle
  System Locale; Encoding = ru_RU (nbdemetra); UTF-8
  Home Directory          = /home/sungreen
  Current Directory       = /usr/local/nbdemetra/bin
  User Directory          = /home/sungreen/.nbdemetra/dev
  Cache Directory         = /home/sungreen/.nbdemetra/dev/var/cache
  Installation            = /usr/local/nbdemetra/platform
                            /usr/local/nbdemetra/nbdemetra
                            /usr/local/nbdemetra/ide
                            /usr/local/nbdemetra/extra
                            /usr/local/nbdemetra/platform
<details>
  Boot & Ext. Classpath   = 
  Application Classpath   = /usr/local/nbdemetra/platform/lib/boot.jar:/usr/local/nbdemetra/platform/lib/org-openide-modules.jar:/usr/local/nbdemetra/platform/lib/org-openide-util.jar:/usr/local/nbdemetra/platform/lib/org-openide-util-lookup.jar:/usr/local/nbdemetra/platform/lib/org-openide-util-ui.jar:/usr/local/nbdemetra/platform/lib/locale/boot_ja.jar:/usr/local/nbdemetra/platform/lib/locale/boot_pt_BR.jar:/usr/local/nbdemetra/platform/lib/locale/boot_ru.jar:/usr/local/nbdemetra/platform/lib/locale/boot_zh_CN.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-modules_ja.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-modules_pt_BR.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-modules_ru.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-modules_zh_CN.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util_ja.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-lookup_ja.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-lookup_ru.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util_pt_BR.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util_ru.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-ui_ja.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-ui_ru.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/usr/local/nbdemetra/platform/lib/locale/org-openide-util_zh_CN.jar
  Startup Classpath       = /usr/local/nbdemetra/platform/core/org-netbeans-libs-asm.jar:/usr/local/nbdemetra/platform/core/org-openide-filesystems.jar:/usr/local/nbdemetra/platform/core/asm-all-5.0.1.jar:/usr/local/nbdemetra/platform/core/core.jar:/usr/local/nbdemetra/platform/core/core-base.jar:/usr/local/nbdemetra/platform/core/org-openide-filesystems-compat8.jar:/usr/local/nbdemetra/platform/core/locale/org-netbeans-libs-asm_pt_BR.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems_ja.jar:/usr/local/nbdemetra/platform/core/locale/core_zh_CN.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems-compat8_pt_BR.jar:/usr/local/nbdemetra/platform/core/locale/core_ru.jar:/usr/local/nbdemetra/platform/core/locale/core-base_ru.jar:/usr/local/nbdemetra/platform/core/locale/org-netbeans-libs-asm_ru.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems-compat8_ru.jar:/usr/local/nbdemetra/platform/core/locale/core_pt_BR.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems-compat8_zh_CN.jar:/usr/local/nbdemetra/platform/core/locale/org-netbeans-libs-asm_ja.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems_zh_CN.jar:/usr/local/nbdemetra/platform/core/locale/core_ja.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems_ru.jar:/usr/local/nbdemetra/platform/core/locale/core-base_zh_CN.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems_pt_BR.jar:/usr/local/nbdemetra/platform/core/locale/org-openide-filesystems-compat8_ja.jar:/usr/local/nbdemetra/platform/core/locale/org-netbeans-libs-asm_zh_CN.jar:/usr/local/nbdemetra/platform/core/locale/core-base_pt_BR.jar:/usr/local/nbdemetra/platform/core/locale/core-base_ja.jar:/usr/local/nbdemetra/nbdemetra/core/locale/core_nbdemetra.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
SEVERE [org.netbeans.core.modules]
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException starting from ModuleCL@1667ee70[eu.europa.ec.joinup.sat.nbdemetra.core] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@568db2f2]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ec.nbdemetra.core.Installer$ProvidersStep.<init>(Installer.java:119)
	at ec.nbdemetra.core.Installer.<init>(Installer.java:57)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openide.util.SharedClassObject.createInstancePrivileged(SharedClassObject.java:658)
	at org.openide.util.SharedClassObject$SetAccessibleAction.run(SharedClassObject.java:1018)
	at org.openide.util.SharedClassObject$SetAccessibleAction.run(SharedClassObject.java:1010)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.openide.util.SharedClassObject.findObject(SharedClassObject.java:532)
Caused: java.lang.IllegalArgumentException
	at org.openide.util.SharedClassObject.findObject(SharedClassObject.java:535)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:465)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:832)
INFO [ec.nbdemetra.ui.Installer]: ChartPanel buffer enabled
SEVERE [org.netbeans.core.modules]
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException starting from ModuleCL@35f8fdb0[eu.europa.ec.joinup.sat.nbdemetra.ui] with possible defining loaders null and declared parents [ModuleCL@5b26d36[org.openide.loaders], ModuleCL@623b57e8[org.netbeans.modules.options.api], ModuleCL@4222f0b1[org.openide.dialogs], ModuleCL@63d5f93b[org.netbeans.modules.settings], org.netbeans.MainImpl$BootClassLoader@568db2f2, ModuleCL@199c4106[org.netbeans.modules.javahelp], ModuleCL@4b055dbb[org.openide.windows], ModuleCL@564a5dda[org.netbeans.core.multiview], ModuleCL@1667ee70[eu.europa.ec.joinup.sat.nbdemetra.core], ModuleCL@39163ed4[org.openide.filesystems.nb], ...8 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ec.nbdemetra.ui.Config.lambda$static$0(Config.java:227)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at ec.nbdemetra.ui.Config.xmlParser(Config.java:170)
	at ec.nbdemetra.ui.Installer.loadConfig(Installer.java:242)
	at ec.nbdemetra.ui.Installer$FormattersStep.onRestore(Installer.java:116)
	at ec.nbdemetra.core.InstallerStep$LookupStep.restore(InstallerStep.java:70)
	at ec.nbdemetra.core.InstallerStep$AllInstallerStep.restore(InstallerStep.java:129)
	at ec.nbdemetra.ui.Installer.restored(Installer.java:78)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:832)
SEVERE [org.netbeans.core.modules]
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException starting from ModuleCL@35f8fdb0[eu.europa.ec.joinup.sat.nbdemetra.ui] with possible defining loaders null and declared parents [ModuleCL@5b26d36[org.openide.loaders], ModuleCL@623b57e8[org.netbeans.modules.options.api], ModuleCL@4222f0b1[org.openide.dialogs], ModuleCL@63d5f93b[org.netbeans.modules.settings], org.netbeans.MainImpl$BootClassLoader@568db2f2, ModuleCL@199c4106[org.netbeans.modules.javahelp], ModuleCL@4b055dbb[org.openide.windows], ModuleCL@564a5dda[org.netbeans.core.multiview], ModuleCL@1667ee70[eu.europa.ec.joinup.sat.nbdemetra.core], ModuleCL@39163ed4[org.openide.filesystems.nb], ...8 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ec.nbdemetra.ui.Config.lambda$static$0(Config.java:227)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at ec.nbdemetra.ui.Config.xmlParser(Config.java:170)
	at ec.nbdemetra.ui.Installer.loadConfig(Installer.java:242)
	at ec.nbdemetra.sa.Installer$DemetraSAStep.restore(Installer.java:31)
	at ec.nbdemetra.sa.Installer.restored(Installer.java:19)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:832)
INFO [org.netbeans.core.startup.NbEvents]: Включение модулей:
	org.openide.util.lookup [8.33.1 201609300101]
	org.openide.util [9.7.1 201609300101]
	org.openide.util.ui [9.6.1 201609300101]
	org.openide.modules [7.48.1 201609300101]
	org.netbeans.api.annotations.common/1 [1.27.1 201609300101]
	org.openide.filesystems [9.10.1 201609300101]
	org.openide.awt [7.67.1 201609300101]
	org.netbeans.api.progress/1 [1.47.1 201609300101]
	org.netbeans.api.progress.nb [1.47.1 201609300101]
	org.openide.dialogs [7.42.1 201609300101]
	org.openide.nodes [7.45.1 201609300101]
	org.openide.windows [6.75.1 201609300101]
	org.netbeans.modules.editor.mimelookup/1 [1.40.1 201609300101]
	org.openide.text [6.67.1 201609300101]
	org.netbeans.swing.tabcontrol [1.56.1 201609300101]
	org.netbeans.swing.outline [1.34.1 201609300101]
	org.openide.explorer [6.62.1 201609300101]
	org.openide.actions [6.39.1 201609300101]
	org.netbeans.modules.queries/1 [1.43.1 201609300101]
	org.netbeans.api.templates [1.7.1 201609300101]
	org.openide.filesystems.nb [9.9.1 201609300101]
	org.openide.loaders [7.66.1 201609300101]
	org.netbeans.api.intent [1.2.1 201609300101]
	org.netbeans.api.io [1.3.1 201609300101]
	org.openide.io [1.49.1 201609300101]
	org.openide.filesystems.compat8 [9.9.1 201609300101]
	org.netbeans.swing.plaf [1.41.1 201609300101]
	org.netbeans.spi.quicksearch [1.27.1 201609300101]
	org.netbeans.modules.templates/1 [1.7.1 201609300101]
	org.netbeans.libs.asm [5.3.1 201609300101]
	org.netbeans.bootstrap/1 [2.76.1 201609300101]
	org.netbeans.core.startup.base [1.62.1.1 1 201609300101]
	org.netbeans.core.startup/1 [1.62.1.1 201609300101]
	org.netbeans.modules.settings/1 [1.49.1 201609300101]
	org.netbeans.modules.sendopts/2 [2.35.1 201609300101]
	org.netbeans.modules.sampler [1.14.1 201609300101]
	org.netbeans.modules.projectapi/1 [1.66.1 201609300101]
	org.netbeans.modules.projectapi.nb [1.3.1 201609300101]
	org.netbeans.modules.project.libraries/1 [1.53.1 201609300101]
	org.netbeans.modules.progress.ui [1.33.1 201609300101]
	org.netbeans.modules.print [7.26.1 201609300101]
	org.netbeans.modules.keyring [1.24.1 201609300101]
	org.netbeans.core/2 [3.51.1 201609300101]
	org.netbeans.modules.options.api/1 [1.45.1 201609300101]
	org.netbeans.modules.options.keymap [1.37.1 201609300101]
	org.netbeans.modules.masterfs/2 [2.55.1.2 2 201609300101]
	org.netbeans.modules.masterfs.ui [2.3.1.2 201609300101]
	org.netbeans.modules.masterfs.nio2 [1.15.1 201609300101]
	org.netbeans.libs.jna/1 [1.44.1 201609300101]
	org.netbeans.modules.masterfs.linux [1.13.1 201609300101]
	org.netbeans.modules.keyring.fallback [1.8.1 201609300101]
	org.netbeans.modules.keyring.impl [1.24.1 201609300101]
	org.netbeans.modules.javahelp/1 [2.41.1 201609300101]
	org.netbeans.modules.favorites/1 [1.46.1 201609300101]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.32.1 201609300101]
	org.netbeans.core.ui/1 [1.45.1 201609300101]
	org.netbeans.core.ide/1 [1.41.1 201609300101]
	org.netbeans.modules.db.metadata.model/1 [1.11.1 201609300101]
	org.netbeans.modules.db/1 [1.66.1.30 30 201609300101]
	org.netbeans.modules.dbapi [1.34.1.30 201609300101]
	org.netbeans.modules.autoupdate.services [1.52.1 201609300101]
	org.netbeans.modules.autoupdate.cli [1.13.1 201609300101]
	org.netbeans.core.windows/2 [2.81.1 201609300101]
	org.netbeans.libs.osgi [1.21.1 201609300101]
	org.netbeans.libs.felix [2.15.1 201609300101]
	org.netbeans.modules.autoupdate.ui [1.45.1 201609300101]
	org.netbeans.modules.core.kit [1.30.1 201609300101]
	org.netbeans.libs.jna.platform/1 [1.14.1 201609300101]
	org.netbeans.core.output2/1 [1.41.1 201609300101]
	org.netbeans.core.network [1.10.1 201609300101]
	org.netbeans.core.netigso [1.31.1 201609300101]
	org.netbeans.core.nativeaccess/1 [1.31.1 201609300101]
	org.netbeans.core.multiview/1 [1.44.1 201609300101]
	org.netbeans.core.multitabs/1 [1.12.1.1 1 201609300101]
	org.netbeans.core.io.ui/1 [1.30.1 201609300101]
	eu.europa.ec.joinup.sat.nbdemetra.core [2.2.2 2.2.2 201901171056]
	eu.europa.ec.joinup.sat.nbdemetra.ui [2.2.2 2.2.2 201901171056]
	eu.europa.ec.joinup.sat.nbdemetra.spreadsheet [2.2.2 2.2.2 201901171057]
	eu.europa.ec.joinup.sat.nbdemetra.sdmx [2.2.2 2.2.2 201901171057]
	eu.europa.ec.joinup.sat.nbdemetra.sa [2.2.2 2.2.2 201901171057]
	eu.europa.ec.joinup.sat.nbdemetra.jdbc [2.2.2 2.2.2 201901171056]
	eu.europa.ec.joinup.sat.nbdemetra.odbc [2.2.2 2.2.2 201901171057]
	eu.europa.ec.joinup.sat.nbdemetra.common [2.2.2 2.2.2 201901171057]
	eu.europa.ec.joinup.sat.nbdemetra.branding [2.2.2 2.2.2 201901171055]
	eu.europa.ec.joinup.sat.nbdemetra.anomalydetection [2.2.2 2.2.2 201901171057]
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ec.tss.tsproviders.utils.DataFormat.<clinit>(DataFormat.java:381)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at org.netbeans.modules.openide.nodes.NodesRegistrationSupport.getClassFromCanonicalName(NodesRegistrationSupport.java:225)
	at org.netbeans.modules.openide.nodes.NodesRegistrationSupport$1.register(NodesRegistrationSupport.java:90)
	at org.netbeans.modules.openide.nodes.NodesRegistrationSupport$AbstractRegistrator.<init>(NodesRegistrationSupport.java:271)
	at org.netbeans.modules.openide.nodes.NodesRegistrationSupport$1.<init>(NodesRegistrationSupport.java:81)
	at org.netbeans.modules.openide.nodes.NodesRegistrationSupport.registerPropertyEditors(NodesRegistrationSupport.java:81)
	at org.openide.nodes.NodeOp.registerPropertyEditors(NodeOp.java:471)
	at org.netbeans.core.CoreBridgeImpl.doRegisterPropertyEditors(CoreBridgeImpl.java:202)
	at org.netbeans.core.CoreBridgeImpl.registerPropertyEditors(CoreBridgeImpl.java:173)
	at org.netbeans.core.startup.Main.start(Main.java:310)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException starting from ModuleCL@1667ee70[eu.europa.ec.joinup.sat.nbdemetra.core] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@568db2f2]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
	... 15 more
</details>

**Comment by charphi** [comment]
Hi. Which JD+ version are you using?

**Comment by sungreen** [comment]
v 2.2.2

**Comment by charphi** [comment]
This problem is solved by the latest version v2.2.3

**Comment by sungreen** [comment]
it works, thanks
